### ISSUE TITLE
When will 3.5.0 be updated?

### ISSUE THREAD

**Issue by how1e** [2nthony/vue-remix-icons#17]
https://remixicon.com/releases

**Comment by 2nthony** [comment]
already is. this repo version not same as upstream repo.

**Comment by how1e** [comment]
I tried using verified-badge but error. Could not find the file.
![image](https://github.com/2nthony/vue-remix-icons/assets/3467006/9d836e40-2f2a-4637-afaa-c204d04e1eae)

**Comment by how1e** [comment]
Sorry my bad. didn't update 3.4.0 properly. now works. thanks.
