### ISSUE TITLE
Icon color in tailwindcss

### ISSUE THREAD

**Issue by mirzobedil** [2nthony/vue-remix-icons#7]
I can't change the icon color.

**Comment by 2nthony** [comment]
> I can't change the icon color.

could you show me the code? i'd like to know how you did

**Comment by smj187** [comment]
Fill works, but a pure tailwind solution I'd prefer

`<div
        class="w-10 h-10 grid place-content-center hover:bg-[#3f3f61] cursor-pointer rounded-md"
      >
        <RiAccountBoxFill class="w-7 h-7" fill="#e5e5e5" />
      </div>`

**Comment by 2nthony** [comment]
yeah, it just render as svg component, i should add this detail in readme.

**Comment by mirzobedil** [comment]
![image](https://user-images.githubusercontent.com/45965774/195619041-aa1ce0dd-7ffb-4fb6-93f4-833eb6b71fdb.png)
It works for me

**Comment by baijii** [comment]
There is also a Tailwind Class for it. Works for me.
```html
<RiHomeLine class="h-5 w-5 text-blue-500 fill-current" />
```

**Comment by mirzobedil** [comment]
Do not use this package, it kills performance.

**Comment by mirzobedil** [comment]
Whenever the web page refreshes, it will load all the icons, including the ones you haven't used.

**Comment by 2nthony** [comment]
![image](https://user-images.githubusercontent.com/19513289/197322408-0e9fc3c0-6fef-449e-b84b-da30baa1ef68.png)

the first build is an empty project, the second build is the project using one icon `RiHomeLine`, see the js file size.

**Comment by mirzobedil** [comment]
You are talking about production, I am talking about development, personally, this package made the development process very difficult for me.

**Comment by 2nthony** [comment]
i updated the docs `usage`, you can import the one you needed.

**Comment by 2nthony** [comment]
> You are talking about production, I am talking about development, personally, this package made the development process very difficult for me.

you can modify your development config to increase the dev performance, as an icon library, all it needs to do is provide icons.

**Comment by mirzobedil** [comment]
Okay thanks 🤝
